version: '3.8'

services:
  wasm-build:
    container_name: 'cfdjs-wasm-builder'
    build:
      context: .
      dockerfile: Dockerfile
      target: cfd_wasm_builder
    environment:
      WASM_SRC: /private/cfd-js-wasm
      WASM_WORK: /private/work/cfd-js-wasm
    working_dir: /private/cfd-js-wasm
    volumes:
      - /private/work
      - .:/private/cfd-js-wasm
    entrypoint: /private/cfd-js-wasm/tools/build_for_release.sh

  wasm-test:
    image: ghcr.io/cryptogarageinc/elements-testing:v0.2.3
    volumes:
      - ./:/workspace
    working_dir: /workspace
    command: /bin/bash -c "npm install && NODE_OPTIONS=--no-experimental-fetch npm run test_example"

  wasm-update-package-lock:
    image: ghcr.io/cryptogarageinc/elements-testing:v0.2.3
    volumes:
      - ./:/workspace
    working_dir: /workspace
    command: /bin/bash -c "./tools/update_package.sh"
